"""Complete regional lists, to fill the gaps the hand-built sheet left.

The sheet had 4 of the 19 Brussels communes and a scattering of research
centres rather than Belgium's universities. Where a sector has a *known,
bounded* membership -- the 19 communes, the Flemish/French university systems,
the EU institutions -- the honest move is to enumerate it rather than hope a
search surfaces the rest.

These lists are curated (they change on the timescale of law, not of hiring)
and carry the context Sarah needs: what the body is, roughly how big, what
language it works in, and why it's relevant. Careers URLs are left to
`discover.py`, which is better at finding them than a hardcoded guess.
"""

# --------------------------------------------------------------- communes
# All 19 communes of the Brussels-Capital Region. Population figures are
# approximate (~2024) and are there to convey scale, not to be precise.
# Language: officially bilingual FR/NL region-wide; the working language of
# each administration is noted where it skews.
BRUSSELS_COMMUNES = [
    ("Anderlecht", 126000, "FR/NL", "Large, diverse, strong social services arm."),
    ("Auderghem / Oudergem", 34000, "FR/NL", "Small, residential, near EU quarter."),
    ("Berchem-Sainte-Agathe / Sint-Agatha-Berchem", 25000, "FR/NL", "Small western commune."),
    ("Bruxelles-Ville / Stad Brussel", 188000, "FR/NL",
     "The city proper. Biggest employer of the 19; runs its own international relations desk."),
    ("Etterbeek", 49000, "FR/NL", "Hosts much of the EU quarter and VUB/ULB campuses."),
    ("Evere", 43000, "FR/NL", "Home to NATO HQ."),
    ("Forest / Vorst", 57000, "FR/NL", "Industrial south-west, active social policy."),
    ("Ganshoren", 25000, "FR/NL", "Small north-western commune."),
    ("Ixelles / Elsene", 88000, "FR/NL",
     "ULB main campus, Matonge (Congolese diaspora), strong cultural/social sector."),
    ("Jette", 53000, "FR/NL", "UZ Brussel campus."),
    ("Koekelberg", 22000, "FR/NL", "Smallest by area."),
    ("Molenbeek-Saint-Jean / Sint-Jans-Molenbeek", 98000, "FR/NL",
     "Large migrant population; heavy investment in integration and youth work."),
    ("Saint-Gilles / Sint-Gillis", 50000, "FR/NL",
     "Dense, diverse, large Spanish/Portuguese/Latin American community."),
    ("Saint-Josse-ten-Noode / Sint-Joost-ten-Node", 28000, "FR/NL",
     "Smallest and densest; very high migrant share."),
    ("Schaerbeek / Schaarbeek", 130000, "FR/NL",
     "Second largest; large Turkish and Moroccan communities."),
    ("Uccle / Ukkel", 85000, "FR/NL", "Affluent south; many international schools."),
    ("Watermael-Boitsfort / Watermaal-Bosvoorde", 25000, "FR/NL", "Green, residential."),
    ("Woluwe-Saint-Lambert / Sint-Lambrechts-Woluwe", 59000, "FR/NL",
     "UCLouvain Brussels health campus."),
    ("Woluwe-Saint-Pierre / Sint-Pieters-Woluwe", 41000, "FR/NL",
     "Affluent east; large expat population."),
]

# Communes just outside the Region that Sarah could plausibly commute to.
BRUSSELS_PERIPHERY = [
    ("Zaventem", 34000, "NL", "Airport commune; many international employers."),
    ("Machelen", 14000, "NL", "Airport-adjacent business parks."),
    ("Vilvoorde", 46000, "NL", "Northern periphery, growing diverse population."),
    ("Grimbergen", 38000, "NL", "Northern periphery."),
    ("Asse", 33000, "NL", "North-west periphery."),
    ("Dilbeek", 43000, "NL", "Western periphery, Flemish Brabant."),
    ("Sint-Pieters-Leeuw", 34000, "NL", "South-west periphery."),
    ("Beersel", 26000, "NL", "Southern periphery."),
    ("Sint-Genesius-Rode / Rhode-Saint-Genese", 18000, "NL/FR",
     "Facility commune; officially Flemish with French-language facilities."),
    ("Hoeilaart", 11000, "NL", "South-east, Sonian Forest."),
    ("Overijse", 25000, "NL", "South-east periphery, sizeable expat community."),
    ("Tervuren", 22000, "NL", "Home to the AfricaMuseum; large expat community."),
    ("Kraainem", 14000, "NL/FR", "Facility commune, eastern edge."),
    ("Wezembeek-Oppem", 14000, "NL/FR", "Facility commune, eastern edge."),
    ("Wemmel", 16000, "NL/FR", "Facility commune, northern edge."),
    ("Drogenbos", 5000, "NL/FR", "Facility commune, southern edge."),
    ("Linkebeek", 5000, "NL/FR", "Facility commune, southern edge."),
    ("Waterloo", 30000, "FR", "Walloon Brabant; large international community."),
    ("Braine-l'Alleud", 40000, "FR", "Walloon Brabant, southern commute."),
    ("La Hulpe", 7000, "FR", "Walloon Brabant; several corporate HQs."),
    ("Rixensart", 22000, "FR", "Walloon Brabant."),
    ("Wavre", 34000, "FR", "Walloon Brabant capital."),
    ("Ottignies-Louvain-la-Neuve", 32000, "FR", "UCLouvain's main campus town."),
    ("Leuven", 102000, "NL", "KU Leuven; 25 min by train from Brussels."),
    ("Mechelen", 87000, "NL", "Between Brussels and Antwerp."),
    ("Halle", 41000, "NL", "Southern periphery, direct rail to Brussels."),
]

# ------------------------------------------------------------- universities
# (name, city, language, students, description, has_anthropology)
# Sarah wants an anthropology PhD, so the anthropology flag drives her filter.
BELGIAN_UNIVERSITIES = [
    ("KU Leuven", "Leuven", "NL/EN", 65000,
     "Belgium's largest university. Social & Cultural Anthropology research group; "
     "IMMRC (Interculturalism, Migration and Minorities Research Centre).", True),
    ("Ghent University (UGent)", "Ghent", "NL/EN", 50000,
     "Large research university. Department of Conflict and Development Studies; "
     "CESSMIR migration centre; strong African studies.", True),
    ("Université libre de Bruxelles (ULB)", "Brussels", "FR/EN", 38000,
     "Francophone, Brussels-based. LAMC (Laboratoire d'anthropologie des mondes "
     "contemporains) is the anthropology centre; strong Latin America links.", True),
    ("UCLouvain", "Louvain-la-Neuve", "FR/EN", 40000,
     "Largest francophone university. LAAP (Laboratoire d'anthropologie prospective) "
     "does prospective/development anthropology.", True),
    ("Vrije Universiteit Brussel (VUB)", "Brussels", "NL/EN", 22000,
     "Brussels Dutch-language university. Brussels School of Governance; "
     "Institute for European Studies; social/cultural anthropology within sociology.", True),
    ("University of Antwerp (UAntwerpen)", "Antwerp", "NL/EN", 22000,
     "CeMIS (Centre for Migration and Intercultural Studies); IOB Institute of "
     "Development Policy.", True),
    ("Université de Liège (ULiège)", "Liège", "FR/EN", 26000,
     "Francophone; LASC (Laboratoire d'anthropologie sociale et culturelle).", True),
    ("Université de Mons (UMONS)", "Mons", "FR", 9000,
     "Francophone; social sciences and translation/interpreting.", False),
    ("Université de Namur (UNamur)", "Namur", "FR", 7000,
     "Francophone; development studies and economics.", False),
    ("Hasselt University (UHasselt)", "Hasselt", "NL/EN", 7000,
     "Smaller Flemish university; no anthropology department.", False),
    ("Université Saint-Louis Bruxelles (UCLouvain Saint-Louis)", "Brussels", "FR", 4000,
     "Francophone Brussels; now part of UCLouvain. Political and social sciences.", False),
    ("College of Europe", "Bruges / Natolin", "EN/FR", 500,
     "Elite postgraduate EU-affairs college. Not a PhD route, but a hiring "
     "employer and a network hub.", False),
    ("Royal Military Academy", "Brussels", "FR/NL", 1000,
     "Defence-oriented; security studies.", False),
    ("Antwerp Management School", "Antwerp", "EN", 2000, "Business school.", False),
    ("Vlerick Business School", "Brussels / Ghent / Leuven", "EN", 2000,
     "Business school with a Brussels campus.", False),
    ("Institute of Tropical Medicine (ITM)", "Antwerp", "EN/NL", 800,
     "Global health research and teaching; strong Global South partnerships and "
     "medical-anthropology adjacent work.", True),
    ("United Nations University - CRIS", "Bruges", "EN", 100,
     "UN University's comparative regional integration studies institute.", False),
    ("IHECS", "Brussels", "FR", 2000,
     "Francophone communication school; applied comms and journalism.", False),
    ("Université ouverte / Open Universiteit", "Multiple", "FR/NL", 0,
     "Distance learning.", False),
]

# Flemish/Walloon university colleges (hogescholen / hautes écoles) worth
# knowing as employers, though not PhD-granting.
BELGIAN_COLLEGES = [
    ("Erasmushogeschool Brussel", "Brussels", "NL", 6000, "Brussels Dutch-language college."),
    ("Odisee", "Brussels / Ghent", "NL", 12000, "Applied sciences, social work."),
    ("HE2B (Haute École Bruxelles-Brabant)", "Brussels", "FR", 8000, "Francophone college."),
    ("Haute École Léonard de Vinci", "Brussels", "FR", 8000, "Francophone college."),
    ("EPHEC", "Brussels", "FR", 5000, "Francophone applied economics college."),
    ("LUCA School of Arts", "Brussels / Ghent", "NL", 4000, "Arts school."),
]

# ---------------------------------------------------------------- hospitals
# (name, city, language, staff, description)
# Big hospitals are large multilingual employers with real non-clinical
# functions: patient mediation, social work, international patient services,
# communications, HR, research administration.
BELGIAN_HOSPITALS = [
    ("UZ Brussel", "Brussels (Jette)", "NL/FR/EN", 3900,
     "VUB's university hospital. Intercultural mediation and social services."),
    ("Cliniques universitaires Saint-Luc (UCLouvain)", "Brussels (Woluwe)", "FR/EN", 5800,
     "UCLouvain's university hospital; large international patient service."),
    ("Hôpital Erasme (ULB)", "Brussels (Anderlecht)", "FR/EN", 3300,
     "ULB's university hospital, part of the H.U.B network."),
    ("H.U.B (Hôpital Universitaire de Bruxelles)", "Brussels", "FR/NL/EN", 6000,
     "Umbrella grouping Erasme, Bordet and HUDERF."),
    ("Institut Jules Bordet", "Brussels (Anderlecht)", "FR/EN", 1200,
     "Cancer institute; strong research arm."),
    ("HUDERF (Queen Fabiola Children's Hospital)", "Brussels (Laeken)", "FR/NL", 1000,
     "Paediatric university hospital."),
    ("CHU Brugmann", "Brussels (Laeken)", "FR/NL", 3300,
     "Large public hospital; very diverse patient population, mediation roles."),
    ("CHU Saint-Pierre", "Brussels (city centre)", "FR/NL/EN", 2900,
     "Public hospital with a major migrant and refugee health programme; "
     "infectious diseases reference centre."),
    ("Chirec (Delta, Braine, Ste-Anne)", "Brussels", "FR/EN", 3000,
     "Private hospital network across Brussels."),
    ("Cliniques de l'Europe / Europa Ziekenhuizen", "Brussels (Uccle/Etterbeek)",
     "FR/NL/EN", 2000, "Bilingual network with a large expat patient base."),
    ("Epicura", "Hainaut", "FR", 2600, "Public hospital network in Hainaut."),
    ("UZ Leuven", "Leuven", "NL/EN", 9000,
     "Belgium's largest hospital; KU Leuven's teaching hospital."),
    ("UZ Gent", "Ghent", "NL/EN", 6500, "UGent's university hospital."),
    ("UZA (Antwerp University Hospital)", "Antwerp", "NL/EN", 3000,
     "University of Antwerp's teaching hospital."),
    ("CHU de Liège", "Liège", "FR", 5500, "ULiège's university hospital."),
    ("CHU UCL Namur", "Namur / Yvoir", "FR", 3000, "UCLouvain's Namur network."),
    ("Institute of Tropical Medicine clinic", "Antwerp", "NL/EN/FR", 500,
     "Travel and tropical medicine clinic attached to ITM."),
]

# ------------------------------------- international orgs with remote hiring
# (name, hq, language, staff, description, remote)
# Sarah asked specifically about worldwide-remote roles: these organisations
# either hire globally-remote or run rosters/consultant pools that don't
# require being in a given city.
INTERNATIONAL_REMOTE = [
    ("United Nations Volunteers (UNV)", "Bonn / global", "EN/FR/ES", 1000,
     "Online Volunteering plus international UNV assignments; explicit remote "
     "programme.", True),
    ("UNDP", "New York / global", "EN/FR/ES", 17000,
     "Large consultant and roster system; many home-based contracts.", True),
    ("UNICEF", "New York / global", "EN/FR/ES", 18000,
     "Consultancy roster with home-based terms of reference.", True),
    ("UNHCR", "Geneva / global", "EN/FR/ES", 20000,
     "Refugee agency; affiliate and consultant schemes, plus a Brussels office.",
     True),
    ("WHO", "Geneva / global", "EN/FR/ES", 8000,
     "Consultant roster; some home-based contracts.", True),
    ("IOM (International Organization for Migration)", "Geneva / global",
     "EN/FR/ES", 20000,
     "Migration agency; large consultant pool and a Brussels regional office.",
     True),
    ("UN Women", "New York / global", "EN/FR/ES", 3000,
     "Gender equality agency; home-based consultancies.", True),
    ("OHCHR", "Geneva / global", "EN/FR/ES", 1500,
     "UN Human Rights; consultant and fellowship routes.", True),
    ("ILO", "Geneva / global", "EN/FR/ES", 3500,
     "Labour standards; external collaboration contracts.", True),
    ("FAO", "Rome / global", "EN/FR/ES", 11000,
     "Food and agriculture; large home-based consultant roster.", True),
    ("WFP", "Rome / global", "EN/FR/ES", 22000,
     "Food assistance; consultant roster and a Brussels liaison office.", True),
    ("UNESCO", "Paris / global", "EN/FR/ES", 2000,
     "Education and culture; consultancies.", True),
    ("UNRWA", "Amman / global", "EN/FR", 30000, "Palestine refugee agency.", False),
    ("UNODC", "Vienna / global", "EN/FR/ES", 2000,
     "Drugs and crime; consultant roster.", True),
    ("UNFPA", "New York / global", "EN/FR/ES", 4000,
     "Population fund; home-based consultancies.", True),
    ("OECD", "Paris", "EN/FR", 3300,
     "Policy research; consultant contracts, some remote.", True),
    ("Council of Europe", "Strasbourg", "EN/FR", 2200,
     "Human rights body; consultant and expert rosters.", True),
    ("OSCE", "Vienna / field", "EN/FR", 3500,
     "Security organisation; secondment and consultant routes.", False),
    ("Amnesty International (International Secretariat)", "London / global",
     "EN/FR/ES", 800, "Distributed secretariat; hires remotely in several hubs.",
     True),
    ("Human Rights Watch", "New York / global", "EN/FR/ES", 550,
     "Hires researchers based in many countries.", True),
    ("Oxfam International", "Nairobi / global", "EN/FR/ES", 10000,
     "Confederation secretariat; several roles are location-flexible.", True),
    ("Save the Children International", "London / global", "EN/FR/ES", 25000,
     "Large international NGO with home-based and roster roles.", True),
    ("Médecins Sans Frontières (Operational Centre Brussels)", "Brussels",
     "FR/EN/ES", 3000,
     "MSF's Brussels operational centre; HQ and field roles.", False),
    ("Norwegian Refugee Council", "Oslo / global", "EN/FR/ES", 15000,
     "NORCAP roster deploys experts globally.", True),
    ("Danish Refugee Council", "Copenhagen / global", "EN/FR", 9000,
     "Standby roster and country offices.", True),
    ("International Crisis Group", "Brussels / global", "EN/FR/ES", 150,
     "Conflict analysis; analysts based in the regions they cover. Brussels HQ.",
     True),
    ("Internews", "Washington / global", "EN/FR/ES", 1000,
     "Media development; many remote roles.", True),
    ("Open Society Foundations", "New York / global", "EN/FR/ES", 800,
     "Grantmaker; hires across hubs including Brussels.", False),
    ("Global Fund", "Geneva", "EN/FR", 900, "Health financing; consultant roster.",
     True),
    ("GAVI", "Geneva", "EN/FR", 500, "Vaccine alliance; some remote roles.", True),
]

# -------------------------------------------- EU trade associations & federations
# (name, sector, languages, description)
# The single biggest gap the profile audit found, and the sector Sarah's own
# briefing ranked first: "this is where the volume is... they hire Policy
# Officer / Policy Advisor roles exactly at her level". Brussels has hundreds;
# these are the large ones that hire continuously.
TRADE_ASSOCIATIONS = [
    ("BusinessEurope", "Cross-sector", "EN/FR",
     "The confederation of European business. The biggest cross-sector voice in "
     "Brussels; hires policy advisers across every file."),
    ("SMEunited", "Cross-sector", "EN/FR", "European association of SMEs and crafts."),
    ("Eurochambres", "Cross-sector", "EN/FR", "Association of European chambers of commerce."),
    ("EuroCommerce", "Retail", "EN/FR", "Retail and wholesale sector association."),
    ("CEFIC", "Chemicals", "EN/FR", "European Chemical Industry Council. Large policy team."),
    ("FoodDrinkEurope", "Food", "EN/FR", "Food and drink industry federation."),
    ("Copa-Cogeca", "Agriculture", "EN/FR", "European farmers and agri-cooperatives."),
    ("DigitalEurope", "Digital", "EN", "Digital technology industry association."),
    ("ETNO", "Telecoms", "EN", "European telecommunications network operators."),
    ("GSMA Europe", "Telecoms", "EN", "Mobile operators' European office."),
    ("Insurance Europe", "Finance", "EN/FR", "European insurance federation."),
    ("European Banking Federation (EBF)", "Finance", "EN/FR", "European banks."),
    ("EFAMA", "Finance", "EN", "European fund and asset management association."),
    ("Eurelectric", "Energy", "EN/FR", "European electricity industry."),
    ("WindEurope", "Energy", "EN", "Wind energy association; strong growth."),
    ("SolarPower Europe", "Energy", "EN", "Solar industry association."),
    ("Hydrogen Europe", "Energy", "EN", "Hydrogen industry association."),
    ("Eurogas", "Energy", "EN", "European gas industry."),
    ("FuelsEurope", "Energy", "EN", "European refining industry."),
    ("EFPIA", "Health", "EN/FR",
     "European pharmaceutical industry federation. Large policy and comms teams."),
    ("MedTech Europe", "Health", "EN", "Medical technology industry."),
    ("Medicines for Europe", "Health", "EN", "Generic and biosimilar medicines."),
    ("EuropaBio", "Health", "EN", "European biotech industry."),
    ("ACEA", "Automotive", "EN/FR", "European automobile manufacturers."),
    ("CLEPA", "Automotive", "EN", "European automotive suppliers."),
    ("Airlines for Europe (A4E)", "Transport", "EN", "European airline association."),
    ("IATA Europe", "Transport", "EN", "Air transport association's European office."),
    ("ECSA", "Transport", "EN", "European Community Shipowners' Associations."),
    ("CER (Community of European Railway)", "Transport", "EN/FR", "European railways."),
    ("IRU", "Transport", "EN/FR", "Road transport union."),
    ("Eurometaux", "Industry", "EN", "European non-ferrous metals association."),
    ("EUROFER", "Industry", "EN", "European steel association."),
    ("Cembureau", "Industry", "EN/FR", "European cement association."),
    ("CEPI", "Industry", "EN", "European paper industry."),
    ("Orgalim", "Industry", "EN", "European technology industries."),
    ("Plastics Europe", "Industry", "EN/FR", "European plastics manufacturers."),
    ("FEAD", "Environment", "EN/FR", "European waste management association."),
    ("Zero Waste Europe", "Environment", "EN", "Environmental network."),
    ("European Environmental Bureau (EEB)", "Environment", "EN/FR",
     "Europe's largest network of environmental citizens' organisations."),
    ("Climate Action Network Europe", "Environment", "EN", "Climate NGO network."),
    ("Transport & Environment", "Environment", "EN", "Clean transport campaign group."),
    ("BEUC", "Consumer", "EN/FR",
     "The European Consumer Organisation. Policy-heavy, well regarded."),
    ("ANEC", "Consumer", "EN", "European consumer voice in standardisation."),
    ("Eurocities", "Local government", "EN/FR",
     "Network of major European cities. Urban policy, migration, inclusion."),
    ("Council of European Municipalities and Regions (CEMR)", "Local government",
     "EN/FR", "European local and regional government association."),
    ("Committee of the Regions liaison offices", "Local government", "EN/FR",
     "Regional representation offices in Brussels."),
    ("European Youth Forum", "Youth", "EN/FR",
     "Platform of youth organisations. Young team, policy and advocacy roles."),
    ("Social Platform", "Social", "EN/FR",
     "The largest platform of European social NGOs."),
    ("Eurodiaconia", "Social", "EN", "European network of churches' social services."),
    ("Caritas Europa", "Social", "EN/FR/ES", "European Caritas network."),
    ("Eurofound liaison", "Social", "EN", "EU agency on living and working conditions."),
    ("SolidarNet / Solidar", "Social", "EN/FR/ES",
     "European network of NGOs advancing social justice."),
    ("European Public Health Alliance (EPHA)", "Health", "EN/FR",
     "Public health NGO network."),
    ("AGE Platform Europe", "Social", "EN/FR", "Network for older people's rights."),
    ("European Disability Forum", "Social", "EN/FR", "Disability rights network."),
    ("European Women's Lobby", "Gender", "EN/FR",
     "The largest umbrella of women's associations in the EU."),
    ("ILGA-Europe", "Human rights", "EN", "LGBTI rights network."),
    ("European Network Against Racism (ENAR)", "Human rights", "EN/FR",
     "Anti-racism network. Direct fit for a rights/migration profile."),
    ("Eurogroup for Animals", "Animal welfare", "EN/FR", "Animal welfare federation."),
]

# ---------------------------------- European & international institutions
# (name, base, languages, description, remote)
# Distinct from the EU institutions proper: intergovernmental bodies that are
# European or international in remit. EUROCONTROL is the type case -- Brussels
# HQ, thousands of staff, and not an EU body at all. Most run their own
# recruitment outside EPSO, which makes them a faster route than a concours.
EUROPEAN_INSTITUTIONS = [
    # --- EU institutions and bodies (the core)
    ("European Commission", "Brussels", "EN/FR/DE",
     "The EU executive. 32,000 staff. EPSO competitions, CAST contract agents, "
     "seconded national experts and traineeships.", False),
    ("European Parliament", "Brussels / Strasbourg / Luxembourg", "EN/FR/all",
     "8,000 staff plus MEP offices. Accredited Parliamentary Assistants are "
     "hired directly by MEPs — no concours, and they move fast.", False),
    ("Council of the European Union", "Brussels", "EN/FR",
     "The member states' institution. 3,000 staff.", False),
    ("European Council", "Brussels", "EN/FR", "Shares the Council's secretariat.", False),
    ("European External Action Service (EEAS)", "Brussels + 145 delegations",
     "EN/FR/ES", "The EU's diplomatic service. Delegations worldwide — the "
     "Latin America desks are a direct fit for Spanish.", False),
    ("European Court of Justice", "Luxembourg", "FR/EN",
     "The EU's court. Legal and language profiles.", False),
    ("European Court of Auditors", "Luxembourg", "EN/FR", "The EU's audit body.", False),
    ("European Central Bank", "Frankfurt", "EN", "The euro area's central bank.", False),
    ("European Investment Bank (EIB)", "Luxembourg", "EN/FR",
     "The EU's lending arm; development finance outside Europe too.", False),
    ("European Investment Fund", "Luxembourg", "EN", "SME finance arm of the EIB.", False),
    ("European Economic and Social Committee (EESC)", "Brussels", "EN/FR",
     "Consultative body for civil society and social partners.", False),
    ("European Committee of the Regions (CoR)", "Brussels", "EN/FR",
     "Consultative body for regional and local government.", False),
    ("European Ombudsman", "Strasbourg / Brussels", "EN/FR",
     "Investigates maladministration in EU bodies.", False),
    ("European Data Protection Supervisor (EDPS)", "Brussels", "EN/FR",
     "The EU's data protection authority.", False),
    ("European Public Prosecutor's Office (EPPO)", "Luxembourg", "EN/FR",
     "Prosecutes crimes against the EU budget.", False),
    ("EPSO (European Personnel Selection Office)", "Brussels", "EN/FR",
     "Runs recruitment for all EU institutions. CAST Permanent is the "
     "open-ended contract-agent route — register and refresh every six months.",
     False),

    # --- EU agencies (Brussels and elsewhere; own recruitment, no concours)
    ("European Defence Agency (EDA)", "Brussels", "EN", "Defence cooperation.", False),
    ("European Education and Culture Executive Agency (EACEA)", "Brussels", "EN/FR",
     "Runs Erasmus+ and Creative Europe.", False),
    ("European Research Executive Agency (REA)", "Brussels", "EN",
     "Manages Horizon Europe research funding.", False),
    ("European Climate, Infrastructure and Environment Agency (CINEA)", "Brussels",
     "EN", "Manages climate and infrastructure programmes.", False),
    ("European Health and Digital Executive Agency (HaDEA)", "Brussels", "EN",
     "Health and digital programmes.", False),
    ("European Innovation Council and SMEs Executive Agency (EISMEA)", "Brussels",
     "EN", "SME and innovation funding.", False),
    ("Frontex", "Warsaw", "EN", "EU border agency. Large recruiter.", False),
    ("EUAA (EU Agency for Asylum)", "Malta", "EN",
     "Asylum agency; deploys experts across member states. Direct migration fit.",
     False),
    ("Europol", "The Hague", "EN", "EU police cooperation agency.", False),
    ("Eurojust", "The Hague", "EN", "Judicial cooperation.", False),
    ("FRA (Fundamental Rights Agency)", "Vienna", "EN",
     "EU fundamental rights agency. Research and rights profiles.", False),
    ("EIGE (European Institute for Gender Equality)", "Vilnius", "EN",
     "Gender equality research and data.", False),
    ("Eurofound", "Dublin", "EN", "Living and working conditions research.", False),
    ("Cedefop", "Thessaloniki", "EN", "Vocational training research.", False),
    ("ETF (European Training Foundation)", "Turin", "EN",
     "Skills and education in partner countries.", False),
    ("EEA (European Environment Agency)", "Copenhagen", "EN", "Environmental data.", False),
    ("ECDC", "Stockholm", "EN", "Disease prevention and control.", False),
    ("EMA (European Medicines Agency)", "Amsterdam", "EN", "Medicines regulator.", False),
    ("EFSA", "Parma", "EN", "Food safety authority.", False),
    ("ECHA", "Helsinki", "EN", "Chemicals agency.", False),
    ("EBA / ESMA / EIOPA", "Paris / Frankfurt", "EN",
     "The three European financial supervisory authorities.", False),
    ("ACER", "Ljubljana", "EN", "Energy regulators' agency.", False),
    ("ENISA", "Athens", "EN", "EU cybersecurity agency.", False),
    ("EU-OSHA", "Bilbao", "EN/ES", "Occupational safety and health agency.", False),
    ("EUIPO", "Alicante", "EN/ES", "Intellectual property office.", False),
    ("CdT (Translation Centre)", "Luxembourg", "EN/FR", "Translation for EU agencies.", False),
    ("EIT (European Institute of Innovation and Technology)", "Budapest", "EN",
     "Innovation networks.", False),

    # --- European intergovernmental organisations (NOT EU bodies)
    ("EUROCONTROL", "Brussels", "EN/FR",
     "European Organisation for the Safety of Air Navigation. Brussels HQ, "
     "~1,900 staff, 41 member states. Intergovernmental, not an EU body — "
     "recruits directly.", False),
    ("NATO", "Brussels (Evere)", "EN/FR",
     "NATO HQ is in Brussels. International Staff hires civilians into policy, "
     "political affairs and public diplomacy.", False),
    ("NATO Parliamentary Assembly", "Brussels", "EN/FR",
     "Interparliamentary body; small secretariat.", False),
    ("NSPA (NATO Support and Procurement Agency)", "Luxembourg", "EN/FR",
     "NATO's logistics agency.", False),
    ("NCIA (NATO Communications and Information Agency)", "Brussels / The Hague",
     "EN", "NATO's IT and comms agency.", False),
    ("ESA (European Space Agency)", "Paris / Noordwijk / Brussels", "EN/FR",
     "Intergovernmental space agency; Brussels liaison office.", False),
    ("EUMETSAT", "Darmstadt", "EN", "European weather satellite organisation.", False),
    ("CERN", "Geneva", "EN/FR", "Particle physics; also non-scientific roles.", False),
    ("EMBL", "Heidelberg", "EN", "European molecular biology laboratory.", False),
    ("ESO (European Southern Observatory)", "Garching / Chile", "EN/ES",
     "Astronomy organisation with major Chilean operations — Spanish relevant.",
     False),
    ("European Patent Office", "Munich / The Hague / Brussels", "EN/FR/DE",
     "Intergovernmental patent organisation; 6,000 staff.", False),
    ("Council of Europe", "Strasbourg", "EN/FR",
     "46 states; human rights, democracy, rule of law. Not an EU body. Runs "
     "its own recruitment and traineeships.", True),
    ("European Court of Human Rights", "Strasbourg", "EN/FR",
     "The Council of Europe's court.", False),
    ("Venice Commission", "Strasbourg", "EN/FR",
     "Council of Europe's constitutional law advisory body.", False),
    ("OSCE", "Vienna / field missions", "EN/FR/ES",
     "57 states; security, elections, human rights. Secondment-heavy.", False),
    ("ODIHR", "Warsaw", "EN", "OSCE's democracy and human rights office; "
     "election observation missions recruit short-term observers.", False),
    ("EFTA Secretariat", "Brussels / Geneva", "EN",
     "European Free Trade Association; Brussels office.", False),
    ("EFTA Surveillance Authority", "Brussels", "EN", "Monitors EEA compliance.", False),
    ("ESM (European Stability Mechanism)", "Luxembourg", "EN",
     "Euro area crisis-resolution fund.", False),
    ("EBRD", "London", "EN/FR/ES",
     "European Bank for Reconstruction and Development.", False),
    ("Benelux Union", "Brussels", "NL/FR", "Benelux secretariat, Brussels.", False),
    ("Western European Union residual bodies", "Brussels", "EN/FR",
     "Small residual structures.", False),
    ("European University Institute", "Florence", "EN/IT",
     "EU-founded postgraduate institute — a genuine PhD route in social and "
     "political sciences.", False),
    ("College of Europe", "Bruges / Natolin", "EN/FR",
     "Postgraduate EU studies; employer and network hub.", False),
    ("International Committee of the Red Cross (ICRC)", "Geneva / Brussels",
     "EN/FR/ES", "ICRC has an EU delegation in Brussels.", False),
    ("IFRC (Red Cross Federation) Europe", "Geneva / Brussels", "EN/FR/ES",
     "Red Cross federation's Brussels office.", False),
    ("Bank for International Settlements", "Basel", "EN", "Central bankers' bank.", False),
    ("WTO", "Geneva", "EN/FR/ES", "World Trade Organization.", False),
    ("WIPO", "Geneva", "EN/FR/ES", "Intellectual property; UN agency.", False),
    ("ITU", "Geneva", "EN/FR/ES", "UN telecommunications agency.", False),
    ("IMO", "London", "EN/FR/ES", "UN maritime agency.", False),
    ("ICAO", "Montreal", "EN/FR/ES", "UN civil aviation agency.", False),
    ("IAEA", "Vienna", "EN/FR/ES", "UN atomic energy agency.", False),
    ("UNIDO", "Vienna", "EN/FR/ES", "UN industrial development.", False),
    ("IFAD", "Rome", "EN/FR/ES", "UN agricultural development fund.", False),
    ("UNOPS", "Copenhagen / global", "EN/FR/ES",
     "UN project services; large roster of home-based contracts.", True),
    ("UNITAR", "Geneva", "EN/FR/ES", "UN training and research institute.", True),
    ("UNU (United Nations University)", "Tokyo / Bruges", "EN",
     "UN University; CRIS institute is in Bruges.", False),
    ("UN Regional Information Centre (UNRIC)", "Brussels", "EN/FR/ES",
     "The UN's information centre for Western Europe. Brussels-based.", False),
    ("UN Liaison Offices in Brussels", "Brussels", "EN/FR",
     "Most UN agencies keep a Brussels liaison to the EU — small teams, "
     "policy and partnership roles.", False),
    ("World Bank Brussels office", "Brussels", "EN/FR/ES",
     "The World Bank's EU liaison office.", False),
    ("IMF Europe office", "Brussels / Paris", "EN", "IMF's European offices.", False),
    ("OECD Brussels", "Brussels / Paris", "EN/FR",
     "OECD's liaison office to the EU.", False),
    ("Interpol", "Lyon", "EN/FR/ES", "International police organisation.", False),
    ("International Organisation of La Francophonie (OIF)", "Paris / Brussels",
     "FR", "Francophone intergovernmental organisation; Brussels office.", False),
    ("Commonwealth Secretariat", "London", "EN", "Commonwealth of Nations.", False),
    ("ACP Secretariat (OACPS)", "Brussels", "EN/FR/ES/PT",
     "Organisation of African, Caribbean and Pacific States. Brussels HQ — "
     "Caribbean and Pacific files, Spanish and Portuguese both useful.", False),
    ("African Union Mission to the EU", "Brussels", "EN/FR", "AU's Brussels mission.", False),
    ("ASEAN Mission to the EU", "Brussels", "EN", "ASEAN's Brussels mission.", False),
    ("Union for the Mediterranean", "Barcelona", "EN/FR/ES",
     "Euro-Mediterranean intergovernmental body; Barcelona-based.", False),
    ("Anna Lindh Foundation", "Alexandria", "EN/FR", "Euro-Med dialogue.", False),
    ("International IDEA", "Stockholm / Brussels", "EN/ES",
     "Democracy support; Brussels office and Latin America programmes.", False),
    ("Global Fund to Fight AIDS, TB and Malaria", "Geneva", "EN/FR", "Health financing.",
     True),
    ("Unitaid", "Geneva", "EN/FR", "Global health.", False),
    ("Gavi, the Vaccine Alliance", "Geneva", "EN/FR", "Vaccine alliance.", True),
]

# ------------------------------------------- political foundations & unions
POLITICAL_FOUNDATIONS = [
    ("Friedrich-Ebert-Stiftung EU Office", "Social democratic", "EN/DE/FR/ES",
     "German SPD-linked foundation; EU office. Latin America programmes worldwide."),
    ("Konrad-Adenauer-Stiftung European Office", "Christian democratic",
     "EN/DE/FR/ES", "CDU-linked; large Latin America network."),
    ("Heinrich-Böll-Stiftung European Union", "Green", "EN/DE/FR",
     "Green political foundation, Brussels office."),
    ("Rosa-Luxemburg-Stiftung Brussels", "Left", "EN/DE/FR/ES",
     "Die Linke-linked; strong Latin America programme."),
    ("Friedrich Naumann Foundation European Dialogue", "Liberal", "EN/DE/FR",
     "FDP-linked liberal foundation."),
    ("Hanns Seidel Stiftung Brussels", "Christian social", "EN/DE", "CSU-linked."),
    ("Foundation for European Progressive Studies (FEPS)", "Social democratic",
     "EN/FR", "The S&D-affiliated think tank."),
    ("Wilfried Martens Centre", "Centre-right", "EN/FR", "The EPP's think tank."),
    ("European Liberal Forum", "Liberal", "EN/FR", "Renew-affiliated foundation."),
    ("Green European Foundation", "Green", "EN/FR", "The Greens/EFA foundation."),
    ("Transform Europe", "Left", "EN/FR/ES", "The Left's political foundation."),
    ("Jean Jaurès Foundation", "Social democratic", "FR/ES",
     "French socialist foundation with a Latin America desk."),
]

TRADE_UNIONS = [
    ("ETUC (European Trade Union Confederation)", "EN/FR/ES",
     "The European trade union confederation. Policy and international roles."),
    ("ETUI (European Trade Union Institute)", "EN/FR",
     "The ETUC's research institute."),
    ("UNI Europa", "EN/FR/ES", "Services sector union federation."),
    ("IndustriAll Europe", "EN/FR", "Industrial workers' federation."),
    ("EPSU", "EN/FR", "European public service unions."),
    ("EFFAT", "EN/FR", "Food, agriculture and tourism unions."),
    ("ETF (European Transport Workers' Federation)", "EN/FR", "Transport unions."),
    ("FGTB / ABVV", "FR/NL", "Belgian socialist trade union."),
    ("CSC / ACV", "FR/NL", "Belgian christian trade union."),
    ("CGSLB / ACLVB", "FR/NL", "Belgian liberal trade union."),
    ("FEB / VBO", "FR/NL/EN", "Federation of Belgian Enterprises."),
    ("BECI (Brussels Enterprises Commerce & Industry)", "FR/NL/EN",
     "Brussels chamber of commerce."),
]

# ------------------------------------------- Spanish / Latin American bodies
# Sarah's Spanish is a deliberate targeting angle rather than a bonus, so these
# get enumerated rather than left to chance.
LATAM_INSTITUTIONS = [
    ("Instituto Cervantes Brussels", "Brussels", "ES/FR/NL",
     "Spain's cultural institute. Language, culture and events programming."),
    ("OEI (Organización de Estados Iberoamericanos) Brussels", "Brussels", "ES/PT/EN",
     "Ibero-American States Organisation; education, science and culture."),
    ("SEGIB (Secretaría General Iberoamericana)", "Madrid", "ES/PT",
     "Ibero-American General Secretariat."),
    ("EU-LAC Foundation", "Hamburg", "ES/EN/PT",
     "EU-Latin America and Caribbean Foundation. Exactly the EU-LAC file."),
    ("CEPAL / ECLAC European office", "Brussels / Santiago", "ES/EN",
     "UN Economic Commission for Latin America; has a Brussels liaison."),
    ("Inter-American Development Bank (IDB) Europe", "Brussels / Washington",
     "ES/EN/PT", "IDB's European office in Brussels."),
    ("CAF - Development Bank of Latin America (Europe)", "Brussels / Caracas",
     "ES/EN", "Latin American development bank's European office."),
    ("Casa de América", "Madrid", "ES", "Spain's Latin America cultural institution."),
    ("Fundación Carolina", "Madrid", "ES", "Spanish scholarships and LatAm cooperation."),
    ("AECID (Spanish Development Cooperation)", "Madrid / Brussels", "ES/EN",
     "Spain's development agency."),
    ("Camões Institute", "Lisbon / Brussels", "PT/ES",
     "Portugal's language and cooperation institute — pairs with her Portuguese."),
    ("Mercosur Mission to the EU", "Brussels", "ES/PT/EN",
     "Mercosur's diplomatic representation."),
    ("CELAC representation", "Brussels", "ES/EN", "CELAC-EU relations."),
    ("Enlazando Alternativas / Latin America networks", "Brussels", "ES/EN",
     "Brussels-based Latin America solidarity networks."),
    ("Grupo Sur", "Brussels", "ES/EN",
     "Coalition of European NGOs working on Latin America. Direct fit."),
    ("Oidhaco", "Brussels", "ES/FR/EN",
     "International office for human rights action on Colombia. Spanish-working, "
     "Brussels-based."),
    ("CIFCA", "Brussels", "ES/EN",
     "Copenhagen Initiative for Central America and Mexico."),
    ("Broederlijk Delen - Latin America", "Brussels", "NL/ES",
     "Belgian NGO with major Latin America programmes."),
    ("Entraide et Fraternité", "Brussels", "FR/ES",
     "Francophone Belgian NGO; Latin America programmes."),
    ("Solsoc (Solidarité Socialiste)", "Brussels", "FR/ES",
     "Belgian socialist solidarity NGO; Latin America."),
    ("FOS (Socialistische Solidariteit)", "Brussels", "NL/ES",
     "Flemish socialist solidarity; Latin America and Cuba programmes."),
]

# ------------------------------------------- cultural institutes & networks
CULTURAL_INSTITUTES = [
    ("British Council Brussels", "Brussels", "EN", "UK cultural relations."),
    ("Goethe-Institut Brüssel", "Brussels", "DE/FR/NL", "German cultural institute."),
    ("Institut français Belgique", "Brussels", "FR", "French cultural institute."),
    ("Alliance Française Bruxelles-Europe", "Brussels", "FR", "French language and culture."),
    ("EUNIC Brussels", "Brussels", "EN/FR",
     "Network of EU national cultural institutes."),
    ("Italian Cultural Institute", "Brussels", "IT/FR", "Italian culture."),
]

# ------------------------------------------- niche government & public bodies
# (name, level, language, description)
# Smaller public bodies that hire policy, comms and research profiles but
# rarely appear on the big boards.
BELGIAN_PUBLIC_BODIES = [
    ("Myria (Federal Migration Centre)", "Federal", "FR/NL/EN",
     "Independent federal migration rights body. Research, policy, advocacy."),
    ("Unia (Interfederal Equal Opportunities Centre)", "Interfederal", "FR/NL/EN",
     "Anti-discrimination body; casework, research, policy."),
    ("Institute for the Equality of Women and Men", "Federal", "FR/NL",
     "Federal gender equality body."),
    ("Federal Institute for Sustainable Development", "Federal", "FR/NL",
     "SDG coordination across federal government."),
    ("Comité P / Comité R", "Federal", "FR/NL",
     "Police and intelligence oversight committees."),
    ("Federal Ombudsman", "Federal", "FR/NL", "Handles complaints against federal bodies."),
    ("Conseil supérieur de la Justice", "Federal", "FR/NL", "Judicial oversight."),
    ("Belgian Development Agency (Enabel)", "Federal", "FR/NL/EN",
     "Belgium's development agency; country programmes and Brussels HQ."),
    ("BIO (Belgian Investment Company for Developing Countries)", "Federal",
     "FR/NL/EN", "Development finance institution."),
    ("Finexpo", "Federal", "FR/NL", "Export credit support."),
    ("Sciensano", "Federal", "FR/NL/EN", "Public health research institute."),
    ("FPS Justice - International cooperation", "Federal", "FR/NL",
     "Judicial cooperation and international files."),
    ("FPS Social Security - International relations", "Federal", "FR/NL",
     "Bilateral social security agreements."),
    ("Fedasil", "Federal", "FR/NL/EN",
     "Reception agency for asylum seekers. Large recruiter; social and policy roles."),
    ("CGRA / CGVS", "Federal", "FR/NL/EN",
     "Office of the Commissioner General for Refugees; protection officers, "
     "country-of-origin researchers."),
    ("Conseil du contentieux des étrangers", "Federal", "FR/NL",
     "Immigration appeals court."),
    ("Office des Étrangers / Dienst Vreemdelingenzaken", "Federal", "FR/NL",
     "Immigration office."),
    ("Brussels International", "Regional (Brussels)", "FR/NL/EN",
     "The Brussels Region's international relations department."),
    ("hub.brussels", "Regional (Brussels)", "FR/NL/EN",
     "Brussels business support agency; international trade attachés."),
    ("Innoviris", "Regional (Brussels)", "FR/NL/EN",
     "Brussels research funding agency."),
    ("perspective.brussels", "Regional (Brussels)", "FR/NL",
     "Brussels planning and statistics bureau."),
    ("Bruxelles Prévention & Sécurité", "Regional (Brussels)", "FR/NL",
     "Regional prevention and security body."),
    ("equal.brussels", "Regional (Brussels)", "FR/NL",
     "Brussels equal opportunities administration."),
    ("Brussels Housing (Bruxelles Logement)", "Regional (Brussels)", "FR/NL",
     "Regional housing administration."),
    ("Iriscare", "Regional (Brussels)", "FR/NL",
     "Brussels health and welfare administration."),
    ("Bruxelles Environnement / Leefmilieu Brussel", "Regional (Brussels)",
     "FR/NL/EN", "Regional environment administration."),
    ("Brussels Studies Institute", "Regional (Brussels)", "FR/NL/EN",
     "Urban research; links the Brussels universities."),
    ("Wallonie-Bruxelles International (WBI)", "Community (FR)", "FR/EN/ES",
     "Francophone Belgium's international relations agency. Strong Latin "
     "America programme — a direct fit for Spanish."),
    ("Flanders Department of Foreign Affairs", "Community (NL)", "NL/EN",
     "Flemish government's international relations department."),
    ("APEFE", "Community (FR)", "FR/ES",
     "Francophone technical cooperation agency; Latin America programmes."),
    ("Délégation générale Wallonie-Bruxelles", "Community (FR)", "FR/ES",
     "Francophone Belgium's overseas delegations."),
    ("CPAS de Bruxelles / OCMW Brussel", "Local (Brussels)", "FR/NL",
     "Public social welfare centre; every commune has one. Large social-work "
     "and integration employer."),
    ("Actiris International", "Regional (Brussels)", "FR/NL/EN",
     "Actiris's international recruitment and EURES arm."),
    ("Bruxelles Formation", "Regional (Brussels)", "FR",
     "Francophone vocational training body."),
    ("VDAB Brussel", "Regional (Brussels)", "NL",
     "Flemish employment service, Brussels branch."),
]
